name: Build and Deploy

on:
  push:
    branches:
      - master  # Trigger the workflow when changes are pushed to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Use the Node.js version your project requires

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the React app
      - name: Build the app
        run: npm run build

      # Step 5: Deploy to the `dist` branch
      - name: Deploy to dist branch
        run: |
          # Configure Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Fetch the latest changes from the origin
          git fetch origin

          # Checkout the dist branch, if it doesn't exist, create it from master
          git checkout dist || git checkout --orphan dist

          # Clean the dist branch (remove all existing files)
          git rm -rf .

          # Copy the contents of the build folder into the dist branch (skip hidden files)
          cp -r build/* ./  # Copy regular files from the build folder

          # Add all changes to Git
          git add --all
          git status  # Print what files are being added

          # Check if any files were added before committing
          if [[ $(git diff --cached --name-only) ]]; then
            git commit -m "Deploy build to dist branch"
          else
            echo "No changes to commit"
            exit 0
          fi

          # Push the changes to the dist branch (force push to overwrite)
          git push origin dist --force
